# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2S',
            fields=[
                ('sno', models.IntegerField(blank=True, null=True)),
                ('bb_id', models.TextField(primary_key=True, serialize=False)),
                ('site_id', models.TextField()),
            ],
            options={
                'db_table': 'b2s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boundingbox',
            fields=[
                ('sno', models.IntegerField(blank=True, null=True)),
                ('bb_id', models.TextField(primary_key=True, serialize=False)),
                ('north', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('south', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('west', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('east', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'boundingbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('sno', models.IntegerField(blank=True, null=True)),
                ('site_id', models.TextField(primary_key=True, serialize=False)),
                ('organizationformalname', models.TextField(blank=True, null=True)),
                ('organizationidentifier', models.TextField(blank=True, null=True)),
                ('monitoringlocationname', models.TextField(blank=True, null=True)),
                ('monitoringlocationtypename', models.TextField(blank=True, null=True)),
                ('monitoringlocationdescriptiontext', models.TextField(blank=True, null=True)),
                ('huceightdigitcode', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('drainageareameasure_measurevalue', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('drainageareameasure_measureunitcode', models.TextField(blank=True, null=True)),
                ('contributingdrainageareameasure_measurevalue', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('contributingdrainageareameasure_measureunitcode', models.TextField(blank=True, null=True)),
                ('latitudemeasure', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitudemeasure', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sourcemapscalenumeric', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('horizontalaccuracymeasure_measurevalue', models.TextField(blank=True, null=True)),
                ('horizontalaccuracymeasure_measureunitcode', models.TextField(blank=True, null=True)),
                ('horizontalcollectionmethodname', models.TextField(blank=True, null=True)),
                ('horizontalcoordinatereferencesystemdatumname', models.TextField(blank=True, null=True)),
                ('verticalmeasure_measurevalue', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('verticalmeasure_measureunitcode', models.TextField(blank=True, null=True)),
                ('verticalaccuracymeasure_measurevalue', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('verticalaccuracymeasure_measureunitcode', models.TextField(blank=True, null=True)),
                ('verticalcollectionmethodname', models.TextField(blank=True, null=True)),
                ('verticalcoordinatereferencesystemdatumname', models.TextField(blank=True, null=True)),
                ('countrycode', models.TextField(blank=True, null=True)),
                ('statecode', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('countycode', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('aquifername', models.TextField(blank=True, null=True)),
                ('formationtypetext', models.TextField(blank=True, null=True)),
                ('aquifertypename', models.TextField(blank=True, null=True)),
                ('constructiondatetext', models.TextField(blank=True, null=True)),
                ('welldepthmeasure_measurevalue', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('welldepthmeasure_measureunitcode', models.TextField(blank=True, null=True)),
                ('wellholedepthmeasure_measurevalue', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='W2B',
            fields=[
                ('sno', models.IntegerField(blank=True, null=True)),
                ('nhd_lake_id', models.TextField()),
                ('bb_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'w2b',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='W2S',
            fields=[
                ('sno', models.IntegerField(blank=True, null=True)),
                ('nhd_lake_id', models.TextField()),
                ('gnis_lake_name', models.TextField(blank=True, null=True)),
                ('site_id', models.TextField(primary_key=True, serialize=False)),
                ('monitoringlocationname', models.TextField(blank=True, null=True)),
                ('isinsidelake', models.NullBooleanField()),
                ('disttoshore_m', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'w2s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waterbodies',
            fields=[
                ('sno', models.IntegerField(blank=True, null=True)),
                ('nhd_lake_id', models.TextField(primary_key=True, serialize=False)),
                ('gnis_name', models.TextField(blank=True, null=True)),
                ('gnis_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_sqkm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('elevation_feet', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ftype', models.IntegerField(blank=True, null=True)),
                ('fcode', models.IntegerField(blank=True, null=True)),
                ('fdate', models.DateField(blank=True, null=True)),
                ('shape_leng_decimaldegrees', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area_sqdecimaldegrees', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'waterbodies',
                'managed': False,
            },
        ),
    ]
