# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisconsin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='waterbodies',
            table='wisconsin.waterbodies',
        ),
    ]
