# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisconsin', '0002_auto_20171001_0841'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='waterbodies',
            table='wisconsin"."waterbodies',
        ),
    ]
