# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisconsin', '0003_auto_20171001_0848'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='b2s',
            table='wisconsin"."b2s',
        ),
        migrations.AlterModelTable(
            name='boundingbox',
            table='wisconsin"."boundingbox',
        ),
        migrations.AlterModelTable(
            name='sites',
            table='wisconsin"."sites',
        ),
        migrations.AlterModelTable(
            name='w2b',
            table='wisconsin"."w2b',
        ),
        migrations.AlterModelTable(
            name='w2s',
            table='wisconsin"."w2s',
        ),
    ]
