# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=b'data')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('template_id', models.CharField(blank=True, max_length=50, null=True)),
                ('current_fragment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'CREATED', b'Workflow created'), (b'STARTED', b'Workflow started'), (b'IN_PROGRESS', b'Workflow in progress'), (b'COMPLETED', b'Workflow completed'), (b'ERROR', b'Error in workflow'), (b'CANCELLED', b'Workflow cancelled')], max_length=50, null=True)),
                ('workflow', models.CharField(blank=True, max_length=2000, null=True)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
